resolver: lts-7.20
packages:
- '.'
extra-deps:
- IOSpec-0.3
- QuickCheck-safe-0.1.0.2
- Stream-0.4.7.2
- arrows-0.4.4.1
- html-entities-1.1.4
- lambdabot-core-5.1.0.1
- lambdabot-haskell-plugins-5.1
- lambdabot-trusted-5.1.0.1
- lazysmallcheck-0.6
- mueval-0.9.3
- prim-uniq-0.1.0.1
- show-0.6
- slack-api-0.12
flags: {}
extra-package-dbs: []
